version: '3.8'
services:
  websockets_demo:
    container_name: websockets_demo
    build:
      context: ./
      dockerfile: websocket_demo/Dockerfile
    env_file:
      - ./.env
#    ports:
#      - "9999:9999"

  tools:
    container_name: tools
    build:
      context: ./
      dockerfile: ./tool_functions/Dockerfile
    env_file:
      - ./.env
#    ports:
#      - "8002:82"

  belhard_tg_bot:
    container_name: belhard_tg_bot
    build:
      context: ./
      dockerfile: bots/belhard/Dockerfile
    env_file:
      - ./bots/belhard/.env
  #    ports:
  #      - ":"
  yoowills_tg_bot:
    container_name: yoowills_tg_bot
    build:
      context: ./
      dockerfile: bots/yoowills/Dockerfile
    env_file:
      - ./bots/yoowills/.env
  #    ports:
  #      - ":"
  a100_chat:
    container_name: a100_chat
    build:
      context: ./
      dockerfile: chats_demo/a100/Dockerfile
    env_file:
      - ./.env
  #    ports:
  #      - ":"
  belhard_chat:
    container_name: belhard_chat
    build:
      context: ./
      dockerfile: chats_demo/belhard/Dockerfile
    env_file:
      - ./.env
  #    ports:
  #      - ":"
  relaxsan_chat:
    container_name: relaxsan_chat
    build:
      context: ./
      dockerfile: chats_demo/relaxsan/Dockerfile
    env_file:
      - ./.env
  #    ports:
  #      - ":"
  yoowills_chat:
    container_name: yoowills_chat
    build:
      context: ./
      dockerfile: chats_demo/yoowills/Dockerfile
    env_file:
      - ./.env
  #    ports:
  #      - ":"

  nginx:
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - websockets_demo
      - tools
      - a100_chat
      - relaxsan_chat