import ChatWidget from './components/ChatWidget/ChatWidget'

function App() {
  return (
    <>
      <ChatWidget />
      <div>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dignissimos quisquam eius enim nesciunt deleniti! Nobis aspernatur sint natus alias dignissimos laboriosam. Placeat amet odio doloribus molestias. Amet eius laborum necessitatibus facere molestias quaerat ex dicta. Quaerat ex quidem quo sed asperiores maxime, facilis reiciendis iste at. Minus perspiciatis molestias quas iste maiores tenetur dicta repudiandae quo aliquam error, facere possimus, amet eaque accusamus explicabo magni culpa vero earum. Dolorum perferendis distinctio enim quaerat suscipit cumque laboriosam tempore alias ut dolores inventore unde in minima deleniti nobis nihil id, qui reiciendis rem voluptas adipisci ipsam iste! Eligendi maxime quidem sapiente minus quam, ipsa rem voluptates dolor earum placeat culpa. Dolore, beatae illum! Vitae commodi earum consequuntur aperiam nihil expedita sed quia.
      </div>
      <div>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dignissimos quisquam eius enim nesciunt deleniti! Nobis aspernatur sint natus alias dignissimos laboriosam. Placeat amet odio doloribus molestias. Amet eius laborum necessitatibus facere molestias quaerat ex dicta. Quaerat ex quidem quo sed asperiores maxime, facilis reiciendis iste at. Minus perspiciatis molestias quas iste maiores tenetur dicta repudiandae quo aliquam error, facere possimus, amet eaque accusamus explicabo magni culpa vero earum. Dolorum perferendis distinctio enim quaerat suscipit cumque laboriosam tempore alias ut dolores inventore unde in minima deleniti nobis nihil id, qui reiciendis rem voluptas adipisci ipsam iste! Eligendi maxime quidem sapiente minus quam, ipsa rem voluptates dolor earum placeat culpa. Dolore, beatae illum! Vitae commodi earum consequuntur aperiam nihil expedita sed quia.
      </div>
      <div>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dignissimos quisquam eius enim nesciunt deleniti! Nobis aspernatur sint natus alias dignissimos laboriosam. Placeat amet odio doloribus molestias. Amet eius laborum necessitatibus facere molestias quaerat ex dicta. Quaerat ex quidem quo sed asperiores maxime, facilis reiciendis iste at. Minus perspiciatis molestias quas iste maiores tenetur dicta repudiandae quo aliquam error, facere possimus, amet eaque accusamus explicabo magni culpa vero earum. Dolorum perferendis distinctio enim quaerat suscipit cumque laboriosam tempore alias ut dolores inventore unde in minima deleniti nobis nihil id, qui reiciendis rem voluptas adipisci ipsam iste! Eligendi maxime quidem sapiente minus quam, ipsa rem voluptates dolor earum placeat culpa. Dolore, beatae illum! Vitae commodi earum consequuntur aperiam nihil expedita sed quia.
      </div>
      <div>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dignissimos quisquam eius enim nesciunt deleniti! Nobis aspernatur sint natus alias dignissimos laboriosam. Placeat amet odio doloribus molestias. Amet eius laborum necessitatibus facere molestias quaerat ex dicta. Quaerat ex quidem quo sed asperiores maxime, facilis reiciendis iste at. Minus perspiciatis molestias quas iste maiores tenetur dicta repudiandae quo aliquam error, facere possimus, amet eaque accusamus explicabo magni culpa vero earum. Dolorum perferendis distinctio enim quaerat suscipit cumque laboriosam tempore alias ut dolores inventore unde in minima deleniti nobis nihil id, qui reiciendis rem voluptas adipisci ipsam iste! Eligendi maxime quidem sapiente minus quam, ipsa rem voluptates dolor earum placeat culpa. Dolore, beatae illum! Vitae commodi earum consequuntur aperiam nihil expedita sed quia.
      </div>
      <div>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dignissimos quisquam eius enim nesciunt deleniti! Nobis aspernatur sint natus alias dignissimos laboriosam. Placeat amet odio doloribus molestias. Amet eius laborum necessitatibus facere molestias quaerat ex dicta. Quaerat ex quidem quo sed asperiores maxime, facilis reiciendis iste at. Minus perspiciatis molestias quas iste maiores tenetur dicta repudiandae quo aliquam error, facere possimus, amet eaque accusamus explicabo magni culpa vero earum. Dolorum perferendis distinctio enim quaerat suscipit cumque laboriosam tempore alias ut dolores inventore unde in minima deleniti nobis nihil id, qui reiciendis rem voluptas adipisci ipsam iste! Eligendi maxime quidem sapiente minus quam, ipsa rem voluptates dolor earum placeat culpa. Dolore, beatae illum! Vitae commodi earum consequuntur aperiam nihil expedita sed quia.
      </div>
      <div>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dignissimos quisquam eius enim nesciunt deleniti! Nobis aspernatur sint natus alias dignissimos laboriosam. Placeat amet odio doloribus molestias. Amet eius laborum necessitatibus facere molestias quaerat ex dicta. Quaerat ex quidem quo sed asperiores maxime, facilis reiciendis iste at. Minus perspiciatis molestias quas iste maiores tenetur dicta repudiandae quo aliquam error, facere possimus, amet eaque accusamus explicabo magni culpa vero earum. Dolorum perferendis distinctio enim quaerat suscipit cumque laboriosam tempore alias ut dolores inventore unde in minima deleniti nobis nihil id, qui reiciendis rem voluptas adipisci ipsam iste! Eligendi maxime quidem sapiente minus quam, ipsa rem voluptates dolor earum placeat culpa. Dolore, beatae illum! Vitae commodi earum consequuntur aperiam nihil expedita sed quia.
      </div>
      <div>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dignissimos quisquam eius enim nesciunt deleniti! Nobis aspernatur sint natus alias dignissimos laboriosam. Placeat amet odio doloribus molestias. Amet eius laborum necessitatibus facere molestias quaerat ex dicta. Quaerat ex quidem quo sed asperiores maxime, facilis reiciendis iste at. Minus perspiciatis molestias quas iste maiores tenetur dicta repudiandae quo aliquam error, facere possimus, amet eaque accusamus explicabo magni culpa vero earum. Dolorum perferendis distinctio enim quaerat suscipit cumque laboriosam tempore alias ut dolores inventore unde in minima deleniti nobis nihil id, qui reiciendis rem voluptas adipisci ipsam iste! Eligendi maxime quidem sapiente minus quam, ipsa rem voluptates dolor earum placeat culpa. Dolore, beatae illum! Vitae commodi earum consequuntur aperiam nihil expedita sed quia.
      </div>
      <div>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dignissimos quisquam eius enim nesciunt deleniti! Nobis aspernatur sint natus alias dignissimos laboriosam. Placeat amet odio doloribus molestias. Amet eius laborum necessitatibus facere molestias quaerat ex dicta. Quaerat ex quidem quo sed asperiores maxime, facilis reiciendis iste at. Minus perspiciatis molestias quas iste maiores tenetur dicta repudiandae quo aliquam error, facere possimus, amet eaque accusamus explicabo magni culpa vero earum. Dolorum perferendis distinctio enim quaerat suscipit cumque laboriosam tempore alias ut dolores inventore unde in minima deleniti nobis nihil id, qui reiciendis rem voluptas adipisci ipsam iste! Eligendi maxime quidem sapiente minus quam, ipsa rem voluptates dolor earum placeat culpa. Dolore, beatae illum! Vitae commodi earum consequuntur aperiam nihil expedita sed quia.
      </div>
      <div>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dignissimos quisquam eius enim nesciunt deleniti! Nobis aspernatur sint natus alias dignissimos laboriosam. Placeat amet odio doloribus molestias. Amet eius laborum necessitatibus facere molestias quaerat ex dicta. Quaerat ex quidem quo sed asperiores maxime, facilis reiciendis iste at. Minus perspiciatis molestias quas iste maiores tenetur dicta repudiandae quo aliquam error, facere possimus, amet eaque accusamus explicabo magni culpa vero earum. Dolorum perferendis distinctio enim quaerat suscipit cumque laboriosam tempore alias ut dolores inventore unde in minima deleniti nobis nihil id, qui reiciendis rem voluptas adipisci ipsam iste! Eligendi maxime quidem sapiente minus quam, ipsa rem voluptates dolor earum placeat culpa. Dolore, beatae illum! Vitae commodi earum consequuntur aperiam nihil expedita sed quia.
      </div>
      <div>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dignissimos quisquam eius enim nesciunt deleniti! Nobis aspernatur sint natus alias dignissimos laboriosam. Placeat amet odio doloribus molestias. Amet eius laborum necessitatibus facere molestias quaerat ex dicta. Quaerat ex quidem quo sed asperiores maxime, facilis reiciendis iste at. Minus perspiciatis molestias quas iste maiores tenetur dicta repudiandae quo aliquam error, facere possimus, amet eaque accusamus explicabo magni culpa vero earum. Dolorum perferendis distinctio enim quaerat suscipit cumque laboriosam tempore alias ut dolores inventore unde in minima deleniti nobis nihil id, qui reiciendis rem voluptas adipisci ipsam iste! Eligendi maxime quidem sapiente minus quam, ipsa rem voluptates dolor earum placeat culpa. Dolore, beatae illum! Vitae commodi earum consequuntur aperiam nihil expedita sed quia.
      </div>
      <div>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dignissimos quisquam eius enim nesciunt deleniti! Nobis aspernatur sint natus alias dignissimos laboriosam. Placeat amet odio doloribus molestias. Amet eius laborum necessitatibus facere molestias quaerat ex dicta. Quaerat ex quidem quo sed asperiores maxime, facilis reiciendis iste at. Minus perspiciatis molestias quas iste maiores tenetur dicta repudiandae quo aliquam error, facere possimus, amet eaque accusamus explicabo magni culpa vero earum. Dolorum perferendis distinctio enim quaerat suscipit cumque laboriosam tempore alias ut dolores inventore unde in minima deleniti nobis nihil id, qui reiciendis rem voluptas adipisci ipsam iste! Eligendi maxime quidem sapiente minus quam, ipsa rem voluptates dolor earum placeat culpa. Dolore, beatae illum! Vitae commodi earum consequuntur aperiam nihil expedita sed quia.
      </div>
      <div>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dignissimos quisquam eius enim nesciunt deleniti! Nobis aspernatur sint natus alias dignissimos laboriosam. Placeat amet odio doloribus molestias. Amet eius laborum necessitatibus facere molestias quaerat ex dicta. Quaerat ex quidem quo sed asperiores maxime, facilis reiciendis iste at. Minus perspiciatis molestias quas iste maiores tenetur dicta repudiandae quo aliquam error, facere possimus, amet eaque accusamus explicabo magni culpa vero earum. Dolorum perferendis distinctio enim quaerat suscipit cumque laboriosam tempore alias ut dolores inventore unde in minima deleniti nobis nihil id, qui reiciendis rem voluptas adipisci ipsam iste! Eligendi maxime quidem sapiente minus quam, ipsa rem voluptates dolor earum placeat culpa. Dolore, beatae illum! Vitae commodi earum consequuntur aperiam nihil expedita sed quia.
      </div>
    </>
  )
}

export default App
